Implement missing interaction features
nyxx-discord/nyxx pull request #173
Opened 2021-08-17 19:45 UTC by l7ssha

# Description

THis PR tracks implementation of missing interaction features

- [x] edit original response
- [x] get original response
- [x] return message when sending followup
- [ ] delete followup
- [ ] delete original response
- [ ] get commands
   - [ ] cached
   - [ ] from api
- [ ] edit single command
- [ ] delete command
- [ ] 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] Ran `dartanalyzer --options analysis_options.yaml .`
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2021-08-17 20:24 UTC, HarryET submitted a review, later dismissed
LGTM, might be worth adding into IHttpEndpoints at some time though?

2021-08-17 21:32 UTC, l7ssha commented
> LGTM, might be worth adding into IHttpEndpoints at some time though?

We could have something like that in Interactions class, yes. Or just move/implement stuff there

2021-08-21 09:30 UTC, HarryET commented
This should include #168 as it seams more applicable than #159

2021-08-22 15:08 UTC, l7ssha commented
its ready for review. Only thing left is documentation.

2021-08-23 11:38 UTC, HarryET requested changes
Have a look at the comment about using _client instead of client.

2021-08-23 11:38 UTC, HarryET commented on nyxx_interactions/lib/src/Interactions.dart
> +  final Nyxx client;
```suggestion
  final Nyxx _client;
```
Use a private variable as the user shouldn't need to access this

2021-08-23 11:42 UTC, HarryET approved these changes

2021-08-23 11:44 UTC, merged