Replace (almost) all parsable enums to an enum-like class
nyxx-discord/nyxx pull request #665
Opened 2024-06-18 19:55 UTC by Rapougnac

# Description

## Connected issues & other potential problems
Closes #661 

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (it's a partial breaking change?)

# Checklist:

- [x] Ran `dart analyze` or `make analyze` and fixed all issues
- [x] Ran `dart format --set-exit-if-changed -l 160 ./lib` or `make format` and fixed all issues
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2024-06-18 21:03 UTC, l7ssha approved these changes

2024-06-19 10:24 UTC, abitofevrything requested changes
Could you also deprecate all the `parse` constructors? They will probably be removed eventually considering that they're now just duplicate functionality.

2024-06-19 10:24 UTC, abitofevrything commented on lib/src/utils/enum_like.dart
> +  bool operator ==(covariant EnumLike<T, U> other) => identical(this, other) || (other is U && other.value == value);
The parameter should not be covariant, it should just be `Object`.

2024-06-24 12:46 UTC, abitofevrything approved these changes

2024-06-24 12:54 UTC, merged